### ISSUE TITLE
make win: mention mingw-w64-tools and gcc-mingw-w64 package in doc/install.txt.in

### ISSUE THREAD

**Issue by psytester** [frankmorgner/openpace#28] opened 2016-01-05 10:57 UTC
Please mention in your newly extended install instruction the usage of mingw packages on the Linux host, where compilation is done.

To be able to start the cross compilation for Windows, it is required to install the `mingw-w64-tools` package on the Linux host to have the `gendef` tool available.
Trying `make win` will fail with `/usr/bin/ld: cannot find -lws2_32` and Google did not highlight the simple solution:
Furthermore the `gcc-mingw-w64` package is required to have the `libws2_32.a` file installed on the Linux host.
Now, this prerequisite should be done.

**Comment by frankmorgner** [comment] 2016-01-05 16:44
the problem is that there are so many Linux derivates that all handle their packages differently, that it's hard to keep up which packages must be installed with what programs. Even on my machine I can only make an educated guess whats the minimum set of packages that need to be installed. And as you pointed out that package naming may change over time and it's different from one distro to an other.

After all, those scripts are only usefull if you know what you're doing as it may require some adjustments. Sorry, but I won't fix that. Maybe at some day I can compile directly with Visual Studio where diversity is not so big...

**Closed by frankmorgner** 2016-01-05 16:44 UTC

**Comment by psytester** [comment] 2016-01-06 07:30
`gendef` tool is no stand alone application, so at least mention the MinGW toolset, as already done for other Tools.
I didn't ask for a specific package name nor its "how to install" ;-)
